travis:
  secure:
    BINSTAR_TOKEN: gJOvyK10DU5EawhPSDZYHjG2riG5Cet+g0vKXxMQSergPphIeVnhewEtWUTcH6yyqaOW+nNv2w6NGqE8Bn3ahNE+ZfuxQyyPfDCKUACVvP1TAq4cbaBAVJS6re13AlREmSbch070tK4f8eJb2s9l2WyTNUB75ZLyLsAVJLOAa0lwVTyIlESEAqJ7ZgrVGNb+Y5WU6z8c7wJ9Aq/q1R2pdFO/iF0yyi6+oRkcbXSYh7knInqrziMrzn2ExS1eL3Ap+0PzzST77+oUuLIs7RPJ4ZrU243seZvmXLioJfuOlzRSswxfAOjFDp9sxsUBSTv3i0xaZMl04JBP0/sjTG++J9F4e365UZN+0ndEISfShsAPcmX+TpJq/jWJ1EZznmt20qykdUC7v7rvKPtilMlVxkQJH62Ul1DZPvexXmQ6h6/kxU8G1dKMimpvgs/YxeVF29xrYbkfYdTqVoSQ1WMZmzHBFMnm/Sp95FWzMaKpoeSkxiKKuSOlK22C+5aiZBl7gm5cktLWYyZX62JytkdGovXnofJ8JgV/XjVHaX6pUqRRsBbAB8RhOKgNFO+GjER9W+8srd74z5bQUw/OdZuqr+kmdWh7d6HoYl2+FE720k2p/2NTP52vpEJInlnb6H1TKKUQPveAtp8/WQcgv06n9/5Cu3py/hsBHX9RiyIKY4U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
