appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QQ2FheuzbIoPX8Q5LBaxPIBMPn2V3A4Lh3LSDXeo+F1TXWPWknF1kf2VOferZYzA3+wNgf2TYgAUvXQzlKyItfbhOzVi1/P81Ey/tjUJ0lEoawwlyirwj2LD9wIxB6ZcH80b9PSxfVDcQsEh9mFTzjgFIAf/SIq6vxiFszJ3qdcwhr6vy203SVTLxuMHlOHe0Mos8jSnj7z6EmUzi+6JY8jXYwME3Vm3z1PSXKs7m31jDqQ743bdnrK5K3gq5eLd2jK2LiU8ovvgQxd5q/tEYEJAkdEpyEpQXennHRmfjns2IU+qikprz/ou+jdwryf7PeQKXUh399gSG1lNuUjvwBVcGWI/K8OloDlk15lDwMBHwHuruR8+RYayiqx5OGPeh/7/nl5zQGuENN58YSysyLDyJcpYJ/b+Q9RmqN2b6UA4j7x3/inCQx137wynpubse/oFSAJP8EzQYs+vntu8I8OzAGRUv952YobEWuZoJlJ/pivuE95+qqQMIZSF0NFdsSq3H3ONcFmp3lyYxkufiCCAnLsJGNvjSe9dbCtyWNB9CqufJH+aK5LtOYERN516Rhnk4b2vObE6vyKvZ+X7BjSlI6k4YbqFyhS/PxLvnO8pcwlQLe8oPs1WnmbNua4qfv473ZDDWBWpeLcGxFzfQGV7yn+ra0CVPNhT0E00vRI=}
